### PR TITLE
Review tree_mft.py with mypy --strict

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Sorry, converting to draft.

`mypy --strict` is being lax with requiring some type signatures along the call path, and it appears to hide a type-incompatibility.

Changing `BinaryParser.Mmap.__enter__` to return `mmap.mmap`, accurately reflecting what it's doing now, causes another type error to arise:

```
indxparse/list_mft.py:385: error: Argument 1 to "MFTEnumerator" has incompatible type "mmap"; expected "array[Any]"  [arg-type]
```

I had thought `mypy --strict` would flag that, or flag the missing signatures on `__enter__`, but apparently not.

`mypy` version: 1.6.0.

I'll work through this tomorrow.

**Comment by williballenthin** [comment]
memory is cheap these days (it wasn't when the script was first written) so i think it might be reasonable to remove the mmap code. just read the whole MFT into memory as a bytearray.

alternatively, since Python 3.2 mmap supports being used as a context manager directly, so we should use that, not our own (probably broken) implementation.

**Comment by ajnelson-nist** [comment]
> memory is cheap these days (it wasn't when the script was first written) so i think it might be reasonable to remove the mmap code. just read the whole MFT into memory as a bytearray.
> 
> alternatively, since Python 3.2 mmap supports being used as a context manager directly, so we should use that, not our own (probably broken) implementation.

Removing `BinaryParser.Mmap` and replacing its usage with two contexts induces some type revisions in `MFT.py`, changing some variables named `buf` and `self._buf` from the uniformly applied `array.array` to a few instances of `mmap.mmap`.  However, I also checked over the information flow from those instances, and things seem to work out - see the second patch I just pushed (`72cfe41`).

So, if the overall decision is to keep `mmap.mmap`, things appear to work out with how they're currently written.

If the overall decision is instead to just read everything into memory, we keep type uniformity at the expense of RAM pressure from significant MFT sizes.

Unfortunately, I'm not sure there is currently a clean solution that lets some paths into the `MFT.py` classes use `mmap`, and others use something else like starting with `array.array`s.  I'm basing this on a not-yet-complete read of [PEP 688](https://peps.python.org/pep-0688/), via [Python typing Issue 593](https://github.com/python/typing/issues/593).  The `Buffer` protocol is only implemented in Python 3.12, and only available as a kind of stub type hint in prior Python versions.  And from [this comment/code block in Typeshed](https://github.com/python/typeshed/blob/5e13bc08e13663f8d44c0fc26a93840811a20f4e/stdlib/_typeshed/__init__.pyi#L239-L247), it looks like there is currently not a difference between readable and writable buffers.

So, it'd be fine to me whichever way this decision goes - keep `mmap`, or read everything up front.  My personal preference is to keep `mmap`, because there might be some cases in the code where this will be a question about disk images.  I can't recall seeing one offhand, but I think as the CLI testing expands, one's gonna be found.

**Comment by williballenthin** [comment]
sounds good to me - lets keep mmap.

I do recall seeing some MFTs from file servers that were multiple GBs, which would put pressure on some laptops these days.

**Comment by ajnelson-nist** [comment]
All righty!  Keeping `mmap`, this is ready for your review and merge.

**Review by williballenthin — APPROVED** [review]
thank you!

**Pull request merged**
